[build]
builder = "nixpacks"
buildCommand = "npm install --prefix apps/backend && npm run build --prefix apps/backend"

[deploy]
startCommand = "node apps/backend/dist/main.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3